version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2-sdk-jessie
    steps:
      - checkout
      - run: cd src && bash build.sh --target=CI --solutionFilePath=Cake.AzureCLI.sln --assemblyVersion=0.0.6